"""
Core Schemas Module.

This module defines the strict Pydantic v2 data models that serve as the 
single source of truth for data flowing through the Legal NLP pipeline. 
These schemas map exactly to the payloads generated by the pipeline's 
seven core processing modules.
"""

from typing import List, Optional,Any,Dict
from pydantic import BaseModel, ConfigDict, Field


class ClauseSpan(BaseModel):
    """
    Represents the exact text and character offsets of a clause extraction 
    from the source document, as generated by the ClauseDetector.
    """
    model_config = ConfigDict(from_attributes=True)

    start_char: int = Field(
        ..., 
        description="Starting character offset in the raw document text."
    )
    end_char: int = Field(
        ..., 
        description="Ending character offset in the raw document text."
    )
    text: str = Field(
        ..., 
        description="The exact text of the extracted span."
    )
    confidence: float = Field(
        ..., 
        ge=0.0,
        le=1.0,
        description="Confidence score of this specific span extraction."
    )


class DetectedClause(BaseModel):
    """
    The foundational unit of the pipeline. Represents a single legal provision.
    Enriched sequentially by Builder, Segmenter, and Classifier.
    """
    model_config = ConfigDict(from_attributes=True)

    clause_id: str = Field(
        ..., 
        description="Unique identifier for the clause."
    )
    text: str = Field(
        ..., 
        description="The normalized text of the legal provision."
    )
    page_number: Optional[int] = Field(
        default=None, 
        description="The page number where the clause is located."
    )
    confidence: float = Field(
        ..., 
        ge=0.0,
        le=1.0,
        description="Overall confidence score for the detected clause."
    )
    spans: List[ClauseSpan] = Field(
        default_factory=list, 
        description="List of text spans making up this clause."
    )
    
    # CUAD Clause Localization Category
    category: Optional[str] = Field(
        default=None, 
        description="CUAD clause detection category."
    )
    
    # Enriched by LEDGAR Clause Classification
    classification_label: Optional[str] = Field(
        default=None, 
        description="Predicted LEDGAR functional legal label."
    )
    classification_score: Optional[float] = Field(
        default=None, 
        ge=0.0,
        le=1.0,
        description="Confidence score from the sequence classification model."
    )


class LegalEntity(BaseModel):
    """
    Represents a specific named entity extracted from a segmented clause 
    via the NERRecognizer, using domain-agnostic naming.
    """
    model_config = ConfigDict(from_attributes=True)

    entity_id: str = Field(
        ..., 
        description="Unique identifier for the extracted entity."
    )
    clause_id: str = Field(
        ..., 
        description="ID of the parent clause where this entity was found."
    )
    text: str = Field(
        ..., 
        description="The exact text or token(s) of the extracted entity."
    )
    label: str = Field(
        ..., 
        description="The recognized NER label (e.g., 'ORG', 'DATE', 'MONEY')."
    )
    confidence: float = Field(
        ..., 
        ge=0.0,
        le=1.0,
        description="Confidence score provided by the NER model."
    )
    start_char: int = Field(
        ..., 
        description="Starting character offset of the entity within the clause."
    )
    end_char: int = Field(
        ..., 
        description="Ending character offset of the entity within the clause."
    )


class LegalRelation(BaseModel):
    """
    Represents a semantic relationship mapped between entities and/or clauses 
    as generated by the RelationExtractor.
    """
    model_config = ConfigDict(from_attributes=True)

    relation_id: str = Field(
        ..., 
        description="Unique identifier for the mapped relationship."
    )
    subject_id: str = Field(
        ..., 
        description="ID of the subject (e.g., a clause_id or entity_id)."
    )
    predicate: str = Field(
        ..., 
        description="The nature of the relationship (e.g., 'GOVERNS', 'CONTAINS')."
    )
    object_id: str = Field(
        ..., 
        description="ID of the object (e.g., an entity_id or clause_id)."
    )
    confidence: float = Field(
        ..., 
        ge=0.0,
        le=1.0,
        description="Confidence score of the relationship extraction."
    )


class ClauseEmbedding(BaseModel):
    """
    A standalone representation of a clause's embedding, as generated by 
    the EmbeddingGenerator for downstream vector storage.
    """
    model_config = ConfigDict(from_attributes=True)

    clause_id: str = Field(
        ..., 
        description="ID of the clause this embedding represents."
    )
    vector: List[float] = Field(
        ..., 
        description="The dense numerical vector."
    )
    model_name: str = Field(
        ..., 
        description="Name of the embedding model used to generate this vector."
    )


class ProcessedLegalDocument(BaseModel):
    """
    The ultimate output of the Legal NLP pipeline. An aggregated, structured 
    representation encompassing clauses, entities, relations, and embeddings.
    """
    model_config = ConfigDict(from_attributes=True)

    document_id: str = Field(
        ..., 
        description="Unique identifier for the processed document."
    )
    filename: str = Field(
        ..., 
        description="The original name of the source file."
    )
    clauses: List[DetectedClause] = Field(
        default_factory=list, 
        description="A flat list of all standardized, classified clauses."
    )
    entities: List[LegalEntity] = Field(
        default_factory=list, 
        description="A flat list of all legal entities extracted via NER."
    )
    relations: List[LegalRelation] = Field(
        default_factory=list, 
        description="Structured semantic links between clauses and entities."
    )
    embeddings: List[ClauseEmbedding] = Field(
        default_factory=list, 
        description="Standalone embedding payloads prepared for vector storage."
    )
    metadata: Dict[str, Any] = Field(
    default_factory=dict,
    description="Additional document metadata and processing information."
    )